### ISSUE TITLE
Syntax Errors in Script

### ISSUE THREAD

**Issue by kasvith** [namila007/Pera_WiFi_Fixer#1]
These were found while running

> $ ./test 
> ./test: line 2: $'\r': command not found                     
> ./test: line 4: $'\r': command not found                     
> ./test: line 8: $'\r': command not found                     
> ./test: line 16: syntax error near unexpected token `$'{\r'' 
> '/test: line 16: `set_dl(){

**Comment by namila007** [comment]
fixed
